### ISSUE TITLE
SparseIso: SparseIso.cpp:119: int main(int, char**): Assertion `system(instance_stream.str().c_str())==0' failed.

### ISSUE THREAD

**Issue by fcamara7** [henryxushi/SparseIso#1]
Hi,
I am trying to run your new tool but I am having problems for some of the (human chromosomes) at the step of the processsam. This does not happen consistently. If I re-run the same chromosome again it sometimes goes through to the end. This is the error message:

sh: line 1: 16301 Killed                  nice /software/rg/el7.2/fcamara/SparseIso_V1.0//tools/processsam --no-coverage -c 1 -g 1 -u 0.05 -d . -o /users/rg/fcamara/projects/hiSeqvsPacBio/sparseisohg38_unfinished.fa/hsAll_Cap1_all_hiSeq.parseiso.chr15/sparseiso_inst /users/rg/fcamara/projects/hiSeqvsPacBio/sparseisohg38_unfinished.fa/hsAll_Cap1_all_hiSeq.parseiso.chr15//sparseiso_sam.sam > /users/rg/fcamara/projects/hiSeqvsPacBio/sparseisohg38_unfinished.fa/hsAll_Cap1_all_hiSeq.parseiso.chr15//inst_log.txt 2>&1

**SparseIso: SparseIso.cpp:119: int main(int, char**): Assertion `system(instance_stream.str().c_str())==0' failed.**

##COMMAND LINE
/usr/share/univage/soldierantcluster/spool/node-hp0402/job_scripts/21229738: line 62: 16285 Aborted                 (core dumped) /software/rg/el7.2/fcamara/SparseIso_V1.0//SparseIso -b /users/rg/fcamara/projects/hiSeqvsPacBio/TMP/sparseisofasta_all${chr2}/hsAll_Cap1_all_hiSeq.${chr2}.bam -o /users/rg/fcamara/projects/hiSeqvsPacBio/sparseisohg38_unfinished.fa/hsAll_Cap1_all_hiSeq.parseiso.${chr2}/ -r s -p 10 --cempath /software/rg/el7.2/fcamara/SparseIso_V1.0//tools --sampath /software/rg/el7.2/fcamara/SparseIso_V1.0//tools

Could you please clarify if possible? I am using hg38 and the bam file corresponding to chr15 with which I am having problems is here: http://genome.crg.es/~fcamara/SPARSEISO/

Please let me know whether you figure out what might be wrong....My BAM files are generated with STAR. I know processsam is a rather old program and I am not sure whether this is why we are getting the inconsistency....

Thanks and regards,

Francisco

**Comment by fcamara7** [comment]
[NQS.seq_id_hg38_unfinished.fa_ad.ev.gz](https://github.com/henryxushi/SparseIso/files/1437474/NQS.seq_id_hg38_unfinished.fa_ad.ev.gz)

(this is an example of a BASH script I am sending to our queuing system)

**Comment by fcamara7** [comment]
UPDATE: By re-running the script for each of the chromosomes on which the program initially failed:
chr1
chr5
chr6
chrX
chr12
chr15
I've managed to get a result. The exception is chr15, on which I no longer get the above-mentioned errors but which seems to be running still 3 hours after I started executing the program (it was much faster for all other -even the larger- chromosomes). I have included the BAM corresponding to the alignments on this chromosome,  plus the compressed **sparseiso_inst.instance** and **inst_log.txt** files in  http://genome.crg.es/~fcamara/SPARSEISO/ for your perusal.

**Comment by henryxushi** [comment]
Hi @fcamara7 ,

Thank you for trying SparseIso. After checking on your script, I would like to know the version you are using. We have updated V1.1 to support STAR alignment, however, I see V1.0 in your script. In V1.1, we have used processsamS instead of processsam (not compatible with STAR and HISAT2) to analyze the bam files. 

Thanks,
Henry

> UPDATE: By re-running the script for each of the chromosomes on which the program initially failed:
> chr1
> chr5
> chr6
> chrX
> chr12
> chr15
> I've managed to get a result. The exception is chr15, on which I no longer get the above-mentioned errors but which seems to be running still 3 hours after I started executing the program (it was much faster for all other -even the larger- chromosomes). I have included the BAM corresponding to the alignments on this chromosome, plus the compressed sparseiso_inst.instance and inst_log.txt files in http://genome.crg.es/~fcamara/SPARSEISO/ for your perusal.

**Comment by fcamara7** [comment]
Hi Henry,

Thanks for your quick reply, I downloaded the script available in the github at the main page (https://github.com/henryxushi/SparseIso/releases/download/V1.0/SparseIso_V1.0.zip) and does indeed point to version 1.0. I will download version 1.1 now, try again and let you know how that goes.

Regards,

Francisco

**Comment by fcamara7** [comment]
Hi again Henry,

The program seems to be working perfectly when using the proper version!

Thanks,

Francisco

**Comment by henryxushi** [comment]
Hi @fcamara7 ,

Thank you for letting me know. I have updated the link on the main page. 

Best,
Henry
