### ISSUE TITLE
Potential bug?

### ISSUE THREAD

**Issue by fcamara7** [henryxushi/SparseIso#2]
Hi again,

I have now run your program successfully (v1.1). However I am obtaining results which are at the very least strange occasionally. It could have something to do with the input data (the BAM file) but I have used the same input with CLASS and stringtie without any noticeable issues. 

I have put the BAM file corresponding to chr15 of hg38 of H.sapiens along with the output files generated by sparseIso in http://genome.crg.es/~fcamara/SPARSEISO.

The main problem is that in a variable number of instances for all chromosomes the end coordinate of exons is equal to "1":

**egrep 'CUFF.45.16' SparseIso.gtf**

chr15	SparseIso	transcript	24167555	24168137	1000	+	.	gene_id "CUFF.45"; transcript_id "CUFF.45.16"; FPKM "19028.591706";
chr15	SparseIso	exon	  **24167555	1**	1000	+	.	gene_id "CUFF.45"; transcript_id "CUFF.45.16"; exon_number "1"; FPKM "19028.591706";
chr15	SparseIso	exon	24167556	24168137	1000	+	.	gene_id "CUFF.45"; transcript_id "CUFF.45.16"; exon_number "2"; FPKM "19028.591706";

In many other instances consecutive exons within the same transcript have the same start/end coordinates:

**egrep 'CUFF.45.15' SparseIso.gtf**

chr15	SparseIso	transcript	24558199	24624105	1000	+	.	gene_id "CUFF.45"; transcript_id "CUFF.45.15"; FPKM "15393.945621";
chr15	SparseIso	exon 	24558199	24558321	1000	+	.	gene_id "CUFF.45"; transcript_id "CUFF.45.15"; exon_number "1"; FPKM "15393.945621";
chr15	SparseIso	exon 	**24566656	24566791**	1000	+	.	gene_id "CUFF.45"; transcript_id "CUFF.45.15"; exon_number "2"; FPKM "15393.945621";
chr15	SparseIso	exon 	 **24566656	24566800**	1000	+	.	gene_id "CUFF.45"; transcript_id "CUFF.45.15"; exon_number "3"; FPKM "15393.945621";
chr15	SparseIso	exon 	**24566792	24566800**	1000	+	.	gene_id "

Would you please take a look at this issues? Do not hesitate to contact me if you require any more info on how I ran the program. I used the pre-compiled SparseIso 1.1.

Thank you very much!

Regards,

Francisco

**Comment by henryxushi** [comment]
Hi @fcamara7 ,

Thank you for letting know. It is indeed a bug when processing the exon boundaries. I have updated a new version with the bug fixed. Thanks.

Best,
Henry

**Comment by fcamara7** [comment]
Hi Henry,

Thanks! I have re-compiled the src code (you have not updated the pre-compiled program, correct?

The issue with consecutive exons starting at the same coordinate seems to have been fixed! However I am still getting "1" as the end coordinate of some exons for every chromosome...

gawk '{if ($5==1)print}' SparseIso.gtf
chr15	SparseIso	exon	 24167555	1	1000	+	.	gene_id "CUFF.45"; transcript_id "CUFF.45.16"; exon_number "1"; FPKM "19028.591706";
chr15	SparseIso	exon	44588638	1	1000	-	.	gene_id "CUFF.221"; transcript_id "CUFF.221.0"; exon_number "1"; FPKM "11.294529";
chr15	SparseIso	exon	49920410	1	1000	-	.	gene_id "CUFF.263"; transcript_id "CUFF.263.0"; exon_number "1"; FPKM "4.623338";
chr15	SparseIso	exon	63276160	1	1000	+	.	gene_id "CUFF.368"; transcript_id "CUFF.368.13"; exon_number "1"; FPKM "1.139783";
chr15	SparseIso	exon	63276160	1	1000	+	.	gene_id "CUFF.368"; transcript_id "CUFF.368.14"; exon_number "1"; FPKM "27.232252";
chr15	SparseIso	exon	63276160	1	1000	+	.	gene_id "CUFF.368"; transcript_id "CUFF.368.15"; exon_number "1"; FPKM "473.046457";
chr15	SparseIso	exon	78840675	1	1000	+	.	gene_id "CUFF.550"; transcript_id "CUFF.550.9"; exon_number "1"; FPKM "1548.546282";
chr15	SparseIso	exon	78840675	1	1000	+	.	gene_id "CUFF.550"; transcript_id "CUFF.550.10"; exon_number "1"; FPKM "545.568079";
chr15	SparseIso	exon	78840675	1	1000	+	.	gene_id "CUFF.550"; transcript_id "CUFF.550.11"; exon_number "1"; FPKM "254.380547";
chr15	SparseIso	exon	78840675	1	1000	+	.	gene_id "CUFF.550"; transcript_id "CUFF.550.13"; exon_number "1"; FPKM "638.469212";
chr15	SparseIso	exon	78840675	1	1000	+	.	gene_id "CUFF.550"; transcript_id "CUFF.550.14"; exon_number "1"; FPKM "1519.635494";
chr15	SparseIso	exon	78840675	1	1000	+	.	gene_id "CUFF.550"; transcript_id "CUFF.550.16"; exon_number "1"; FPKM "12.319294";
chr15	SparseIso	exon	78840675	1	1000	+	.	gene_id "CUFF.550"; transcript_id "CUFF.550.17"; exon_number "1"; FPKM "191.547115";

Can you please double-check in case I did something wrong? 

Thanks,

Francisco

**Comment by henryxushi** [comment]
Hi @fcamara7 ,

I have updated the package. Could you try the pre-compiled package at https://github.com/henryxushi/SparseIso/releases/download/V1.1/SparseIso_V1.1.zip ?

I also tried to compile the code and run on your data, but cannot replicate your error. Please let me know if you have more questions. Thanks!

Best,
Henry

**Comment by fcamara7** [comment]
Hi Henry,

Thanks for the quick reply. I have tried running the pre-compiled version you just sent me but it complains of bamtools and boost libraries which apparently do not correspond to the ones the program was compiled with?

example: ./SparseIso: error while loading shared libraries: libbamtools.so.2.4.0: cannot open shared object file: No such file or directory

In the meantime I will re-compile the code and try re-running..It's odd you cannot replicate the error...The dependencies should not have to do with this, correct? By the way, I have compiled the code on centOS 7.

dependencies:  Eigen/3.2.3
Boost/1.61.0
BamTools/2.2.3
GCCcore/4.9.3


Thanks and regards,

Francisco

**Comment by henryxushi** [comment]
Hi @fcamara7 ,

Sorry for the library incompatibility issue. I forgot that I have updated the system and software packages. Right now, I have updated the pre-compiled binaries and it should work fine. For your compile issue, I may need to test more on centOS system, as the package works fine on Ubuntu 12.04 and 16.04. Will let you know when I figure out the problem. Thanks.

Best,
Henry

**Comment by fcamara7** [comment]
No problem, and thanks for fixing it! As for the issue with the "1" as the
end coordinate on a few exons, do let me know. Apparently it only happens
when the exon is made up of just one nucleotide?! Might have to do with
centos yes. Will contact the system admins to see if they can test it on a
different platform.

Cheers,

Francisco

**Comment by henryxushi** [comment]
Hi @fcamara7 ,

There is indeed a bug related to exon boundaries of single nucleotide exons. I did not notice that as it is very rare. I have fixed the bug for current codes and releases. If you have any more questions, please let me know. Thanks.

Best,
Henry

**Comment by fcamara7** [comment]
Thanks Henry,

I'll check it tomorrow when I'm back at work.

Cheers,

Francisco
